import 'package:flutter/cupertino.dart';
import 'package:newsify/generated/l10n.dart';

enum NewsCountry {
  argentina(name: 'Argentina', country: 'ar'),
  australia(name: 'Australia', country: 'au'),
  austria(name: 'Austria', country: 'at'),
  belgium(name: 'Belgium', country: 'be'),
  brazil(name: 'Brazil', country: 'br'),
  bulgaria(name: 'Bulgaria', country: 'bg'),
  canada(name: 'Canada', country: 'ca'),
  china(name: 'China', country: 'cn'),
  colombia(name: 'Colombia', country: 'co'),
  czechRepublic(name: 'Czech Republic', country: 'cz'),
  egypt(name: 'Egypt', country: 'eg'),
  france(name: 'France', country: 'fr'),
  germany(name: 'Germany', country: 'de'),
  greece(name: 'Greece', country: 'gr'),
  hongKong(name: 'Hong Kong', country: 'hk'),
  hungary(name: 'Hungary', country: 'hu'),
  india(name: 'India', country: 'in'),
  indonesia(name: 'Indonesia', country: 'id'),
  ireland(name: 'Ireland', country: 'ie'),
  israel(name: 'Israel', country: 'il'),
  italy(name: 'Italy', country: 'it'),
  japan(name: 'Japan', country: 'jp'),
  latvia(name: 'Latvia', country: 'lv'),
  lithuania(name: 'Lithuania', country: 'lt'),
  malaysia(name: 'Malaysia', country: 'my'),
  mexico(name: 'Mexico', country: 'mx'),
  morocco(name: 'Morocco', country: 'ma'),
  netherlands(name: 'Netherlands', country: 'nl'),
  newZealand(name: 'New Zealand', country: 'nz'),
  nigeria(name: 'Nigeria', country: 'ng'),
  norway(name: 'Norway', country: 'no'),
  philippines(name: 'Philippines', country: 'ph'),
  poland(name: 'Poland', country: 'pl'),
  portugal(name: 'Portugal', country: 'pt'),
  romania(name: 'Romania', country: 'ro'),
  saudiArabia(name: 'Saudi Arabia', country: 'sa'),
  serbia(name: 'Serbia', country: 'rs'),
  singapore(name: 'Singapore', country: 'sg'),
  slovakia(name: 'Slovakia', country: 'sk'),
  slovenia(name: 'Slovenia', country: 'si'),
  southAfrica(name: 'South Africa', country: 'za'),
  southKorea(name: 'South Korea', country: 'kr'),
  sweden(name: 'Sweden', country: 'se'),
  switzerland(name: 'Switzerland', country: 'ch'),
  taiwan(name: 'Taiwan', country: 'tw'),
  thailand(name: 'Thailand', country: 'th'),
  turkey(name: 'Turkey', country: 'tr'),
  uAE(name: 'UAE', country: 'ae'),
  ukraine(name: 'Ukraine', country: 'ua'),
  unitedKingdom(name: 'United Kingdom', country: 'gb'),
  unitedStates(name: 'United States', country: 'us'),
  venuzuela(name: 'Venuzuela', country: 've');

  const NewsCountry({required this.name, required this.country});

  final String name;
  final String country;

  String getName(BuildContext context){
    return switch(this){

      NewsCountry.argentina => S.of(context).argentina,
      NewsCountry.australia => S.of(context).australia,
      NewsCountry.austria => S.of(context).austria,
      NewsCountry.belgium => S.of(context).belgium,
      NewsCountry.brazil => S.of(context).brazil,
      NewsCountry.bulgaria => S.of(context).bulgaria,
      NewsCountry.canada => S.of(context).canada,
      NewsCountry.china => S.of(context).china,
      NewsCountry.colombia => S.of(context).colombia,
      NewsCountry.czechRepublic => S.of(context).czech_republic,
      NewsCountry.egypt => S.of(context).egypt,
      NewsCountry.france => S.of(context).france,
      NewsCountry.germany => S.of(context).germany,
      NewsCountry.greece => S.of(context).greece,
      NewsCountry.hongKong => S.of(context).hong_kong,
      NewsCountry.hungary => S.of(context).hungary,
      NewsCountry.india => S.of(context).india,
      NewsCountry.indonesia => S.of(context).indonesia,
      NewsCountry.ireland => S.of(context).ireland,
      NewsCountry.israel => S.of(context).israel,
      NewsCountry.italy => S.of(context).italy,
      NewsCountry.japan => S.of(context).japan,
      NewsCountry.latvia => S.of(context).latvia,
      NewsCountry.lithuania => S.of(context).lithuania,
      NewsCountry.malaysia => S.of(context).malaysia,
      NewsCountry.mexico => S.of(context).mexico,
      NewsCountry.morocco => S.of(context).morocco,
      NewsCountry.netherlands => S.of(context).netherlands,
      NewsCountry.newZealand => S.of(context).new_zealand,
      NewsCountry.nigeria => S.of(context).nigeria,
      NewsCountry.norway => S.of(context).norway,
      NewsCountry.philippines => S.of(context).philippines,
      NewsCountry.poland => S.of(context).poland,
      NewsCountry.portugal => S.of(context).portugal,
      NewsCountry.romania => S.of(context).romania,
      NewsCountry.saudiArabia => S.of(context).saudi_arabia,
      NewsCountry.serbia => S.of(context).serbia,
      NewsCountry.singapore => S.of(context).singapore,
      NewsCountry.slovakia => S.of(context).slovakia,
      NewsCountry.slovenia => S.of(context).slovenia,
      NewsCountry.southAfrica => S.of(context).south_africa,
      NewsCountry.southKorea => S.of(context).south_korea,
      NewsCountry.sweden => S.of(context).sweden,
      NewsCountry.switzerland => S.of(context).switzerland,
      NewsCountry.taiwan => S.of(context).taiwan,
      NewsCountry.thailand => S.of(context).thailand,
      NewsCountry.turkey => S.of(context).turkey,
      NewsCountry.uAE => S.of(context).u_a_e,
      NewsCountry.ukraine => S.of(context).ukraine,
      NewsCountry.unitedKingdom => S.of(context).united_kingdom,
      NewsCountry.unitedStates => S.of(context).united_states,
      NewsCountry.venuzuela => S.of(context).venuzuela,
    };
  }
}
